#!/bin/bash

JAR="./out/tools/assembly.dest/out.jar"

if [ -f $JAR ]; 
then
    java -jar $JAR "$@"
else
    echo "No jar found. Please run:"
    echo
    echo "$ ./mill '{rtl,tools}.assembly'"

    exit 1
fi