/* SPDX-License-Identifier: Apache-2.0 */
/* Copyright © 2019-2022 Tensil AI Company */

#pragma once

#ifdef TENSIL_TARGET_ULTRA96_V2

#define TENSIL_PLATFORM_ENABLE_XTIME
#define TENSIL_PLATFORM_ENABLE_FATFS

#define TENSIL_PLATFORM_INSTRUCTION_AXI_DMA_DEVICE_ID XPAR_AXIDMA_0_DEVICE_ID
#define TENSIL_PLATFORM_SAMPLE_AXI_DMA_DEVICE_ID XPAR_AXIDMA_1_DEVICE_ID

#define TENSIL_PLATFORM_PROG_BUFFER_BASE 0x1000000
#define TENSIL_PLATFORM_PROG_BUFFER_HIGH 0x40000000

#define TENSIL_PLATFORM_DRAM_BUFFER_BASE TENSIL_PLATFORM_PROG_BUFFER_HIGH
#define TENSIL_PLATFORM_DRAM_BUFFER_HIGH 0x50000000

#define TENSIL_PLATFORM_SAMPLE_BUFFER_BASE TENSIL_PLATFORM_DRAM_BUFFER_HIGH
#define TENSIL_PLATFORM_SAMPLE_BUFFER_HIGH 0x60000000

#define TENSIL_PLATFORM_AFIFM_RDCTRL 0x0
#define TENSIL_PLATFORM_AFIFM_WRCTRL 0x14

#define TENSIL_ZYNQ_MPSOC_FABRIC_WIDTH_MASK 0xfffffffc

#define TENSIL_ZYNQ_MPSOC_FABRIC_WIDTH_32 0b10
#define TENSIL_ZYNQ_MPSOC_FABRIC_WIDTH_64 0b01
#define TENSIL_ZYNQ_MPSOC_FABRIC_WIDTH_128 0b00

#define TENSIL_PLATFORM_AFIFM0_ADDR XPAR_PSU_AFI_2_S_AXI_BASEADDR
#define TENSIL_PLATFORM_AFIFM1_ADDR XPAR_PSU_AFI_4_S_AXI_BASEADDR

#define TENSIL_PLATFORM_AFIFM0_FABRIC_WIDTH TENSIL_ZYNQ_MPSOC_FABRIC_WIDTH_128
#define TENSIL_PLATFORM_AFIFM1_FABRIC_WIDTH TENSIL_ZYNQ_MPSOC_FABRIC_WIDTH_128

#define TENSIL_PLATFORM_AFIFM0_FABRIC_WIDTH_MASK                               \
    TENSIL_ZYNQ_MPSOC_FABRIC_WIDTH_MASK
#define TENSIL_PLATFORM_AFIFM1_FABRIC_WIDTH_MASK                               \
    TENSIL_ZYNQ_MPSOC_FABRIC_WIDTH_MASK

#endif

#ifdef TENSIL_TARGET_ARTY_A7_100T

#define TENSIL_PLATFORM_ENABLE_FATFS

#define TENSIL_PLATFORM_INSTRUCTION_AXI_DMA_DEVICE_ID XPAR_AXIDMA_0_DEVICE_ID
#define TENSIL_PLATFORM_SAMPLE_AXI_DMA_DEVICE_ID XPAR_AXIDMA_1_DEVICE_ID

#define TENSIL_PLATFORM_PROG_BUFFER_BASE 0x80400000
#define TENSIL_PLATFORM_PROG_BUFFER_HIGH 0x88000000

#define TENSIL_PLATFORM_DRAM_BUFFER_BASE TENSIL_PLATFORM_PROG_BUFFER_HIGH
#define TENSIL_PLATFORM_DRAM_BUFFER_HIGH 0x8c000000

#define TENSIL_PLATFORM_SAMPLE_BUFFER_BASE TENSIL_PLATFORM_DRAM_BUFFER_HIGH
#define TENSIL_PLATFORM_SAMPLE_BUFFER_HIGH 0x8fffffff

#define TENSIL_PLATFORM_STOPWATCH_TIMER_DEVICE_ID XPAR_TMRCTR_0_DEVICE_ID

#endif

#ifdef TENSIL_TARGET_PYNQ_Z1

#define TENSIL_PLATFORM_ENABLE_XTIME
// #define TENSIL_PLATFORM_ENABLE_FATFS

// #define TENSIL_PLATFORM_INSTRUCTION_AXI_DMA_DEVICE_ID XPAR_AXIDMA_0_DEVICE_ID
// #define TENSIL_PLATFORM_SAMPLE_AXI_DMA_DEVICE_ID XPAR_AXIDMA_1_DEVICE_ID
#define TENSIL_PLATFORM_INSTRUCTION_AXI_DMA_DEVICE_ID XPAR_AXIDMA_1_DEVICE_ID
#define TENSIL_PLATFORM_SAMPLE_AXI_DMA_DEVICE_ID XPAR_AXIDMA_0_DEVICE_ID

#define TENSIL_PLATFORM_PROG_BUFFER_BASE 0x00400000
#define TENSIL_PLATFORM_PROG_BUFFER_HIGH 0x08000000

#define TENSIL_PLATFORM_DRAM_BUFFER_BASE TENSIL_PLATFORM_PROG_BUFFER_HIGH
#define TENSIL_PLATFORM_DRAM_BUFFER_HIGH 0x0c000000

#define TENSIL_PLATFORM_SAMPLE_BUFFER_BASE TENSIL_PLATFORM_DRAM_BUFFER_HIGH
#define TENSIL_PLATFORM_SAMPLE_BUFFER_HIGH 0x0fffffff

#define TENSIL_PLATFORM_AFIFM_RDCTRL 0x0
#define TENSIL_PLATFORM_AFIFM_WRCTRL 0x14

#define TENSIL_ZYNQ_7000_FABRIC_WIDTH_MASK 0xfffffffe

#define TENSIL_ZYNQ_7000_FABRIC_WIDTH_32 0b1
#define TENSIL_ZYNQ_7000_FABRIC_WIDTH_64 0b0

#define TENSIL_PLATFORM_AFIFM0_ADDR 0xF8008000
#define TENSIL_PLATFORM_AFIFM1_ADDR 0xF800A000

#define TENSIL_PLATFORM_AFIFM0_FABRIC_WIDTH TENSIL_ZYNQ_7000_FABRIC_WIDTH_64
#define TENSIL_PLATFORM_AFIFM1_FABRIC_WIDTH TENSIL_ZYNQ_7000_FABRIC_WIDTH_64

#define TENSIL_PLATFORM_AFIFM0_FABRIC_WIDTH_MASK                               \
    TENSIL_ZYNQ_7000_FABRIC_WIDTH_MASK
#define TENSIL_PLATFORM_AFIFM1_FABRIC_WIDTH_MASK                               \
    TENSIL_ZYNQ_7000_FABRIC_WIDTH_MASK

#endif

#if defined(TENSIL_PLATFORM_ENABLE_FATFS)
#define TENSIL_PLATFORM_ENABLE_FILE_SYSTEM
#endif
