/* SPDX-License-Identifier: Apache-2.0 */
/* Copyright © 2019-2022 Tensil AI Company */

#pragma once

#ifdef TENSIL_TARGET_ULTRA96_V2

#define TENSIL_PLATFORM_DECODER_TIMEOUT 100
#define TENSIL_PLATFORM_SAMPLE_BLOCK_SIZE 1024

#define TENSIL_PLATFORM_ENABLE_XTIME
#define TENSIL_PLATFORM_ENABLE_FILE_SYSTEM

#define TENSIL_PLATFORM_INSTRUCTION_AXI_DMA_DEVICE_ID XPAR_AXIDMA_0_DEVICE_ID
#define TENSIL_PLATFORM_SAMPLE_AXI_DMA_DEVICE_ID XPAR_AXIDMA_1_DEVICE_ID

#define TENSIL_PLATFORM_PROG_BUFFER_BASE 0x1000000
#define TENSIL_PLATFORM_PROG_BUFFER_HIGH 0x40000000

#define TENSIL_PLATFORM_DRAM_BUFFER_BASE TENSIL_PLATFORM_PROG_BUFFER_HIGH
#define TENSIL_PLATFORM_DRAM_BUFFER_HIGH 0x50000000

#define TENSIL_PLATFORM_SAMPLE_BUFFER_BASE TENSIL_PLATFORM_DRAM_BUFFER_HIGH
#define TENSIL_PLATFORM_SAMPLE_BUFFER_HIGH 0x60000000

#endif

#ifdef TENSIL_TARGET_PYNQ_Z1

#define TENSIL_PLATFORM_DECODER_TIMEOUT 100
#define TENSIL_PLATFORM_SAMPLE_BLOCK_SIZE 1024

#define TENSIL_PLATFORM_ENABLE_XTIME
// #define TENSIL_PLATFORM_ENABLE_FILE_SYSTEM

// #define TENSIL_PLATFORM_INSTRUCTION_AXI_DMA_DEVICE_ID XPAR_AXIDMA_0_DEVICE_ID
// #define TENSIL_PLATFORM_SAMPLE_AXI_DMA_DEVICE_ID XPAR_AXIDMA_1_DEVICE_ID
#define TENSIL_PLATFORM_INSTRUCTION_AXI_DMA_DEVICE_ID XPAR_AXIDMA_1_DEVICE_ID
#define TENSIL_PLATFORM_SAMPLE_AXI_DMA_DEVICE_ID XPAR_AXIDMA_0_DEVICE_ID

#define TENSIL_PLATFORM_PROG_BUFFER_BASE 0x00400000
#define TENSIL_PLATFORM_PROG_BUFFER_HIGH 0x08000000

#define TENSIL_PLATFORM_DRAM_BUFFER_BASE TENSIL_PLATFORM_PROG_BUFFER_HIGH
#define TENSIL_PLATFORM_DRAM_BUFFER_HIGH 0x0c000000

#define TENSIL_PLATFORM_SAMPLE_BUFFER_BASE TENSIL_PLATFORM_DRAM_BUFFER_HIGH
#define TENSIL_PLATFORM_SAMPLE_BUFFER_HIGH 0x0fffffff

#endif

#ifdef TENSIL_TARGET_ARTY_A7_100T

#include <stdint.h>
#include <stdio.h>
struct flash;
int flash_read(struct flash *flash, uint8_t *buffer, size_t size, size_t *read_size);
#define TENSIL_PLATFORM_FLASH_TYPE struct flash*
#define TENSIL_PLATFORM_FLASH_READ flash_read

#define TENSIL_PLATFORM_INSTRUCTION_AXI_DMA_DEVICE_ID XPAR_AXIDMA_0_DEVICE_ID

#define TENSIL_PLATFORM_SAMPLE_BLOCK_SIZE 1024
#define TENSIL_PLATFORM_DECODER_TIMEOUT 100

#define TENSIL_PLATFORM_PROG_BUFFER_BASE 0x80400000
#define TENSIL_PLATFORM_PROG_BUFFER_HIGH 0x88000000

#define TENSIL_PLATFORM_DRAM_BUFFER_BASE TENSIL_PLATFORM_PROG_BUFFER_HIGH
#define TENSIL_PLATFORM_DRAM_BUFFER_HIGH 0x8c000000

#define TENSIL_PLATFORM_STOPWATCH_TIMER_DEVICE_ID XPAR_TMRCTR_0_DEVICE_ID

#endif

#ifdef TENSIL_TARGET_CMOD_A7_35T

#include <stdint.h>
#include <stdio.h>
struct flash;
int flash_read(struct flash *flash, uint8_t *buffer, size_t size, size_t *read_size);
#define TENSIL_PLATFORM_FLASH_TYPE struct flash*
#define TENSIL_PLATFORM_FLASH_READ flash_read

#define TENSIL_PLATFORM_INSTRUCTION_AXI_DMA_DEVICE_ID XPAR_AXIDMA_0_DEVICE_ID

#define TENSIL_PLATFORM_SAMPLE_BLOCK_SIZE 1024
#define TENSIL_PLATFORM_DECODER_TIMEOUT 100

#define TENSIL_PLATFORM_PROG_BUFFER_BASE 0x60010000
#define TENSIL_PLATFORM_PROG_BUFFER_HIGH 0x60020000

#define TENSIL_PLATFORM_DRAM_BUFFER_BASE TENSIL_PLATFORM_PROG_BUFFER_HIGH
#define TENSIL_PLATFORM_DRAM_BUFFER_HIGH 0x60080000

#endif

