/* SPDX-License-Identifier: Apache-2.0 */
/* Copyright © 2019-2022 Tensil AI Company */

#pragma once

#define TENSIL_ARCHITECTURE_DATA_TYPE             TENSIL_DATA_TYPE_FP16BP8
#define TENSIL_ARCHITECTURE_ARRAY_SIZE            16
#define TENSIL_ARCHITECTURE_DRAM0_DEPTH           4194304
#define TENSIL_ARCHITECTURE_DRAM1_DEPTH           4194304
#define TENSIL_ARCHITECTURE_LOCAL_DEPTH           20480
#define TENSIL_ARCHITECTURE_ACCUMULATOR_DEPTH     4096
#define TENSIL_ARCHITECTURE_SIMD_REGISTERS_DEPTH  1
#define TENSIL_ARCHITECTURE_STRIDE0_DEPTH         8
#define TENSIL_ARCHITECTURE_STRIDE1_DEPTH         8
