#pragma once

#define TENSIL_ARCHITECTURE_DATA_TYPE             TENSIL_DATA_TYPE_FP16BP8
#define TENSIL_ARCHITECTURE_ARRAY_SIZE            32
#define TENSIL_ARCHITECTURE_DRAM0_DEPTH           2097152
#define TENSIL_ARCHITECTURE_DRAM1_DEPTH           2097152
#define TENSIL_ARCHITECTURE_LOCAL_DEPTH           16384
#define TENSIL_ARCHITECTURE_ACCUMULATOR_DEPTH     4096
#define TENSIL_ARCHITECTURE_SIMD_REGISTERS_DEPTH  1
#define TENSIL_ARCHITECTURE_STRIDE0_DEPTH         8
#define TENSIL_ARCHITECTURE_STRIDE1_DEPTH         8
